export const CHANGE_TAB = "change_tab"
export const USER_UPDATE = "user_update"
export const USER_RESET = "user_reset"
export const SEND_MESSAGE = "send_message"
export const RECEIVE_MESSAGE_LIST = "receive_message_list"
export const RECEIVE_MESSAGE = "receive_message"
